name: pro3
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  permission_handler: ^11.0.1
  path_provider: ^2.1.1
  device_info_plus: ^9.1.1
  web_socket_channel: ^2.4.0
  network_info_plus: ^4.0.2
  image: ^4.1.3
  path: ^1.8.3
  screen_brightness: ^0.2.2
  sqflite: ^2.3.2+1
  file_selector: ^1.0.3
  open_file: ^3.2.1





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
